win_mingw_x64:
	make -f win_mingw_x64.mk all

run_win_mingw_x64:
	make -f win_mingw_x64.mk run

linux_gcc_x86:
	make -f linux_gcc_x86.mk all

run_linux_gcc_x86:
	make -f linux_gcc_x86.mk run

linux_gcc_x64:
	make -f linux_gcc_x64.mk all

run_linux_gcc_x64:
	make -f linux_gcc_x64.mk run

linux_gcc_arm:
	make -f linux_gcc_arm.mk all

run_linux_gcc_arm:
	make -f linux_gcc_arm.mk run

linux_gcc_arm64:
	make -f linux_gcc_arm64.mk all

run_linux_gcc_arm64:
	make -f linux_gcc_arm64.mk run

macos_clang_x64:
	make -f macos_clang_x64.mk all

run_macos_clang_x64:
	make -f macos_clang_x64.mk run

clean:
	make -f win_mingw_x64.mk clean
	make -f linux_gcc_x86.mk clean
	make -f linux_gcc_x64.mk clean
	make -f linux_gcc_arm.mk clean
	make -f linux_gcc_arm64.mk clean
	make -f macos_clang_x64.mk clean
